### ISSUE TITLE
NTP

### ISSUE THREAD

**Issue by jcolandr** [CiscoUcs/KUBaM#1]
NTP is not properly starting preventing the ansible play book from completeing. I had to ssh to each node and manually restart ntp and manually update it with the proper server.

**Comment by vallard** [comment]
Hmm... I  will take a look.  Thanks for writing up the issue.

**Comment by vallard** [comment]
I'm having a hard time reproducing this.  Can you show output?  Sorry to put you through those paces.  I'll be making this part easier anyway soon!

**Comment by vallard** [comment]
closed due to new API architecture.  This will be handled differently going forward.
