### ISSUE TITLE
UCSM 4 Support

### ISSUE THREAD

**Issue by SergeySypalo** [CiscoUcs/KUBaM#16]
Hi guys,
Just upgraded UCSM and got this error:
Unsupported UCS firmware version: 4.0(1a). Please update to at least 3.0

**Comment by vallard** [comment]
Will be fixing this in the version 2 release.  Thanks for letting me know.  Sorry for delay!

**Comment by vallard** [comment]
This was fixed with the last commit.  Will verify.

**Comment by vallard** [comment]
Verified works now with UCS 4
