### ISSUE TITLE
Docs out of date

### ISSUE THREAD

**Issue by travisn08** [CiscoUcs/KUBaM#17]
Hi - the docs site is a bit old, still mentions March updating...  https://ciscoucs.github.io/site/

**Comment by vallard** [comment]
Thanks I'll look into this one.  The whole site really needs more updating.  Is there a part that you are looking for more and I can prioritize?

**Comment by travisn08** [comment]
Hi - what caught my eye most were the dates mentioned on the root pages because it gave the impression of an abondoned project.

**Comment by vallard** [comment]
Yeah sorry about that. Slow but steady!  Contributions welcome!

**Comment by vallard** [comment]
Think we are ok now with docs as current as they are.
