### ISSUE TITLE
ESXi 6.7 issue with vMedia Policy

### ISSUE THREAD

**Issue by tkelkermans** [CiscoUcs/KUBaM#21]
Hello,

First of all, I would like to thank you for the work you've done with KuBAM, it's a great tool !
I'm trying to make it work with ESXi (6.7 U1), and I have an issue with the vMedia policy.
As seen in the documentation, I configured a CDD one, with the service-profile-name as image parameter. Unfortunately it does not seem to work (iso file is $service-profile-name .iso). When I set it manually (complete path), it seems to work.

Could you please help me resolve this ?

Thanks,

Tristan

**Comment by tkelkermans** [comment]
Sorry, just a typo in the documentation where it does not state that we have to add a "/" at the end of the remote path.

**Comment by vallard** [comment]
I’m out of office this week with limited connectivity but will get on next week and have a crack. Sorry for delay

**Comment by vallard** [comment]
Cool. I'm trying to find the typo in the docs so I can fix it.  Can you
tell me which page you were looking at?  Thanks for your help!
